def generate_code(ir):
    """
    IR se Python code generate karta hai.
    Clean, readable Python code output karta hai.
    """

    lines = []
    lines.append("# Auto-generated Python Code")
    lines.append("# Generated by Multilingual Natural Language Compiler")
    lines.append("")

    op_symbol = {
        "ADD": "+",
        "SUB": "-",
        "MUL": "*",
        "DIV": "/"
    }

    op_name = {
        "ADD": "Addition",
        "SUB": "Subtraction",
        "MUL": "Multiplication",
        "DIV": "Division"
    }

    for stmt in ir:
        op = stmt["op"]

        # ── ARITHMETIC ──────────────────────────────────
        if op in ["ADD", "SUB", "MUL", "DIV"]:
            symbol = op_symbol[op]
            name = op_name[op]
            result = stmt["result"]
            a1 = _fmt(stmt["arg1"])
            a2 = _fmt(stmt["arg2"])

            lines.append(f"# {name}")
            lines.append(f"{result} = {a1} {symbol} {a2}")
            lines.append(f"print(f\"{result} = {{{result}}}\")")
            lines.append("")

        # ── IF ───────────────────────────────────────────
        elif op == "IF":
            cond = stmt["condition"]
            left = _fmt(cond["left"])
            right = _fmt(cond["right"])
            operator = cond["op"]

            then = stmt["then"]
            then_sym = op_symbol[then["op"]]
            then_a1 = _fmt(then["arg1"])
            then_a2 = _fmt(then["arg2"])
            then_res = then["result"]

            lines.append(f"# IF Condition")
            lines.append(f"if {left} {operator} {right}:")
            lines.append(f"    {then_res} = {then_a1} {then_sym} {then_a2}")
            lines.append(f"    print(f\"{then_res} = {{{then_res}}}\")")

            if stmt["else"]:
                el = stmt["else"]
                else_sym = op_symbol[el["op"]]
                else_a1 = _fmt(el["arg1"])
                else_a2 = _fmt(el["arg2"])
                else_res = el["result"]

                lines.append(f"else:")
                lines.append(f"    {else_res} = {else_a1} {else_sym} {else_a2}")
                lines.append(f"    print(f\"{else_res} = {{{else_res}}}\")")

            lines.append("")

        # ── LOOP ─────────────────────────────────────────
        elif op == "LOOP":
            count = stmt["count"]
            body = stmt["body"]
            body_sym = op_symbol[body["op"]]
            body_a1 = _fmt(body["arg1"])
            body_a2 = _fmt(body["arg2"])
            body_res = body["result"]

            lines.append(f"# Loop {count} times")
            lines.append(f"for i in range({count}):")
            lines.append(f"    {body_res} = {body_a1} {body_sym} {body_a2}")
            lines.append(f"    print(f\"Iteration {{i+1}}: {body_res} = {{{body_res}}}\")")
            lines.append("")

    return "\n".join(lines)


def _fmt(val):
    """Number ko int ya float format mein string banata hai"""
    if isinstance(val, float) and val == int(val):
        return str(int(val))
    return str(val)
